language: node_js
addons:
  apt:
    packages:
      - libcairo2-dev
      - libgif-dev
      - libjpeg8-dev
  firefox: "latest"
  googlechrome: "latest"
before_install:
  - chmod 1777 /dev/shm
  - export CHROME_SANDBOX=/opt/google/chrome/chrome-sandbox
  - wget https://googledrive.com/host/0B5VlNZ_Rvdw6NTJoZDBSVy1ZdkE -O $CHROME_SANDBOX
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
node_js:
  - "0.10"
script: "make ci"
after_script:
  - make coverage
sudo: false
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d55e363c3fc707460225
